language: php

php:
  - 7
  - 7.1
  - hhvm

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer update --prefer-dist --ignore-platform-reqs

script:
  - |
    if 
      [[ $TRAVIS_PHP_VERSION = "hhv"* ]];
    then
      hhvm -v Eval.EnableHipHopSyntax=true ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml;
    else
      ./vendor/bin/phpunit --disallow-test-output --report-useless-tests --coverage-clover ./clover.xml;
    fi
  - |
    if 
      [[ $TRAVIS_PHP_VERSION = "hhv"* ]]; 
    then
      echo 'skip build for hhvm';
    else
      if 
        php -i |grep -qE xdebug; 
      then 
        ./vendor/bin/humbug; 
      fi
    fi

matrix:
  allow_failures:
    - php: hhvm

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml
  
sudo: false
